import { Routes } from '@angular/router';
import { HomeComponent } from '../home/home.component';
import { CompanyAuthGuard } from '../_guards/auth.guard';
import { UserMaintenaceComponent } from '../user/user-maintenance.component';
import { AccessDeniedComponent } from '../error/access-denied.component';
import { AddAssetComponent } from '../asset/addasset/addasset.component';
import { AddNewMobileComponent } from '../fleet/add-new-mobile/add-new-mobile.component';


export const SECURE_ROUTES: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full', data: { shouldDetach: false } },
  { path: 'home', component: HomeComponent, canActivate: [CompanyAuthGuard], data: { title: 'Home', shouldDetach: false } },
  { path: 'company', loadChildren: () => import('../company/company.module').then(m => m.CompanyModule) },
  { path: 'role-maintenance', loadChildren: () => import('../role-maintenance/role-maintenance.module').then(m => m.RoleMaintenanceModule) },
  { path: 'dispatchlog-report', loadChildren: () => import('../dispatch/dispatcherror-log/dispatcherror-log.module').then(m => m.DispatchErrorLogModule) },
  { path: 'pending-dispatch', loadChildren: () => import('../dispatch/pending-dispatch/pending-dispatch.module').then(m => m.PendingDispatchModule) },
  { path: 'login-history-report', loadChildren: () => import('../admin-reports/tracking-report/tracking-report.module').then(m => m.TrackingReportModule) },
  { path: 'login-history-detail-report/:fd/:td/:cg', loadChildren: () => import('../admin-reports/tracking-detail-report/tracking-detail-report.module').then(m => m.TrackingDetailReportModule) },
  { path: 'over-usage-report', loadChildren: () => import('../admin-reports/over-usage-report/over-usage-report.module').then(m => m.OverUsageReportModule) },
  { path: 'data-allowance-limit', loadChildren: () => import('../admin-reports/data-allowance-limit/data-allowance-limit.module').then(m => m.DataAllowanceLimitModule) },
  { path: 'client-transactions', loadChildren: () => import('../admin-reports/client-transaction/client-transaction.module').then(m => m.ClientTransactionModule) },
  { path: 'total-billing-analysis', loadChildren: () => import('../report/call-class-analysis/call-class-analysis.module').then(tb => tb.CallClassAnalysisReportModule) },
  { path: 'total-billing-summary', loadChildren: () => import('../report/total-billing-summary-report/total-billing-summary-report.module').then(tb => tb.TotalBillingSummaryReportModule) },
  { path: 'total-billing-itemised', loadChildren: () => import('../report/call-class-itemised-bill/call-class-itemised-bill.module').then(tb => tb.CallClassItemisedBillModule) },
  //{ path: 'user-maintenance', loadChildren: () => import('../user/user-maintenance.module').then(m => m.UserMaintenanceModule) },
  { path: 'user-maintenance', component: UserMaintenaceComponent, canActivate: [CompanyAuthGuard], data: { title: 'User Maintenance', shouldDetach: false } },
  { path: 'upload-invoice', loadChildren: () => import('../upload-invoice/upload-invoice.module').then(m => m.UploadInvoiceModule) },
  { path: 'newcompany-setup', loadChildren: () => import('../newcompany-setup/newcompany-setup.module').then(m => m.NewcompanySetUpModule) },
  { path: 'new-connections', loadChildren: () => import('../order/new-connection/new-connection.module').then(m => m.NewConnectionModule) },
  { path: 'hardware-order', loadChildren: () => import('../order/hardware.orders/hardware.orders.module').then(m => m.HardwareOrdersModule) },
  { path: 'email-config', loadChildren: () => import('../emailconfig/emailconfig.module').then(m => m.EmailConfigModule) },
  { path: 'client-agreement', loadChildren: () => import('../client-agreement/client-agreement.module').then(m => m.ClientUserAgreementModule) },
  { path: 'order-confirmation', loadChildren: () => import('../order/order-confirmation/order-confirmation.module').then(m => m.OrderConfirmationModule) },
  { path: 'client-configuration', loadChildren: () => import('../client/client.module').then(m => m.ClientModule) },
  { path: 'access-denied', component: AccessDeniedComponent, data: { title: 'Access Denied', shouldDetach: false } },
  { path: 'manage-fleet', loadChildren: () => import('../fleet/fleet.module').then(m => m.FleetModule) },
  { path: 'update-mobile-detail', loadChildren: () => import('../fleet/update-mobile/update-mobile.module').then(m => m.UpdateMobileModule) },
  { path: 'add-new-mobile', component: AddNewMobileComponent, canActivate: [CompanyAuthGuard], data: { title: 'Add New Mobile', shouldDetach: false } },
  //{ path: 'add-new-mobile', loadChildren: () => import('../fleet/add-new-mobile/add-new-mobile.module').then(m => m.AddNewMobileModule) },
  { path: 'asset-summary', loadChildren: () => import('../asset/asset.summary.module').then(m => m.AssetSummaryModule) },
  { path: 'add-asset', component: AddAssetComponent, canActivate: [CompanyAuthGuard], data: { title: 'Add New Asset', shouldDetach: false } },
  { path: 'update-asset-details', loadChildren: () => import('../asset/updateasset-details/updateasset-details.module').then(m => m.UpdateAssetDetailsModule) },
  { path: 'manager-supplier', loadChildren: () => import('../asset/asset-supplier/asset-supplier.module').then(m => m.AssetSupplierModule) },
  { path: 'dashboard', loadChildren: () => import('../dashboard/dashboard.module').then(m => m.DashboardModule) },
  { path: 'invoice', loadChildren: () => import('../invoice/invoice.module').then(m => m.InvoiceModule) },
  { path: 'invoice-itemised-bill/:id/:mn', loadChildren: () => import('../invoice/invoice-itemisedbill/invoice.itemisedbill.module').then(m => m.InvoiceItemisedBillModule) },

  { path: 'asset-change-report', loadChildren: () => import('../report/asset-change-report/asset-change-report.module').then(m => m.AssetChangeReportModule) },
  { path: 'billing-average-trend', loadChildren: () => import('../report/billing-average-trend/billing-average-trend.module').then(m => m.BillingAverageTrendModule) },
  { path: 'billing-historical-usage', loadChildren: () => import('../report/billing-historical-usage-report/billing-historical-usage-report.module').then(m => m.BillingHistoricalUsageReportModule) },
  { path: 'billing-usage-trend', loadChildren: () => import('../report/billing-usage-trend/billing-usage-trend.module').then(m => m.BillingUsageTrendModule) },
  { path: 'total-billing-information', loadChildren: () => import('../report/call-class/call-class.module').then(m => m.CallClassModule) },
  { path: 'most-dialled-report', loadChildren: () => import('../report/most-dialled-number/most-dialled-number.module').then(m => m.MostDialledNumberReportModule) },
  { path: 'most-dialled-number-detail-report/:dn/:fd/:td', loadChildren: () => import('../report/most-dialled-number/most-dialled-number-detail/most-dialled-number-detail.module').then(m => m.MostDialledNumberDetailReportModule) },
  { path: 'non-geographic-report', loadChildren: () => import('../report/non-geographic/non-geographic.module').then(m => m.NonGeographicReportModule) },
  { path: 'non-geographic-detail-report/:dn/:fd/:td', loadChildren: () => import('../report/non-geographic/non-geographic-detail/non-geographic-detail.module').then(m => m.NonGeographicDetailReportModule) },
  { path: 'non-geographic-itemised/:dn/:su', loadChildren: () => import('../report/non-geographic/non-geographic-itemised/non-geographic-itemised.module').then(m => m.NonGeoraphyItemisedModule) },
  { path: 'international-report', loadChildren: () => import('../report/international-report/international-report.module').then(m => m.InternationalReportModule) },
  { path: 'roamed-report', loadChildren: () => import('../report/roamed-report/roamed-report.module').then(m => m.RoamedReportModule) },
  { path: 'spend-usage-report', loadChildren: () => import('../report/spend-usage-report/spend-usage-report.module').then(m => m.SpendUsageReportModule) },
  { path: 'top-usage-report', loadChildren: () => import('../report/top-usage-report/top-usage-report.module').then(m => m.TopUsageReportModule) },
  { path: 'zero-usage-report', loadChildren: () => import('../report/zero-usage-report/zero-usage-report.module').then(m => m.ZeroUsageReportModule) },
  { path: 'euro-world-report', loadChildren: () => import('../report/euro-world-traveller-report/euro-world-traveller-report.module').then(m => m.EuroWorldTravellerReportModule) },
  { path: 'euro-world-itemised-bill/:id', loadChildren: () => import('../report/euro-world-traveller-report/euro-world-itemisedbill/euro-world-itemisedbill.module').then(m => m.EuroWorldItemisedBillModule) },
  { path: 'charge-report', loadChildren: () => import('../report/charge-report/charge-report.module').then(m => m.ChargeReportModule) },
  { path: 'charge-detail-report/:fromdate/:todate/:cg', loadChildren: () => import('../report/charge-report/charge-detail-report/charge-detail-report.module').then(m => m.ChargeDetailReportModule) },
  { path: 'handset-total-report', loadChildren: () => import('../report/handset-total-report/handset-total-report.module').then(m => m.HandsetTotalReportModule) },
  { path: 'zero-usage-by-month', loadChildren: () => import('../report/zero-usage-by-month-report/zero-usage-by-month-report.module').then(m => m.ZeroUsageByMonthReportModule) },
  { path: 'data-history-report', loadChildren: () => import('../report/data-history-report/data-history-report.module').then(m => m.DataHistoryReportModule) },
  { path: 'roamed-report-by-country', loadChildren: () => import('../report/roamed-report-by-country/roamed-report-by-country.module').then(m => m.RoamedReportByCountryModule) },
  { path: 'international-report-by-destination', loadChildren: () => import('../report/international-report-by-destination/international-report-by-destination.module').then(m => m.InternationalReportByDestinationModule) },
  { path: 'reporting-group-historic-cost', loadChildren: () => import('../report/history-cost-by-reporting-group/history-cost-by-reporting-group.module').then(m => m.HistoryCostByReportingGroupModule) },
  { path: 'data-summary-report', loadChildren: () => import('../report/data-summary-report/data-summary-report.module').then(m => m.DataSummaryReportModule) },
  { path: 'roamed-report-itemised/:ctry', loadChildren: () => import('../report/roamed-report-itemised/roamed-report-itemised.module').then(m => m.RoamedReportItemisedModule) },
  { path: 'international-report-by-destination-detail', loadChildren: () => import('../report/international-report-by-destination-detail/international-report-by-destination-detail.module').then(m => m.InternationalReportByDestinatinDetailModule) },
  { path: 'mobile-change-report', loadChildren: () => import('../report/mobile-change-report/mobile-change-report.module').then(m => m.MobileChangeReportModule) },
  { path: 'order-report', loadChildren: () => import('../report/order-report/order-report.module').then(m => m.OrderReportModule) },
  { path: 'care-report', loadChildren: () => import('../report/care-report/care-report.module').then(m => m.CareReportModule) },
  { path: 'disconnection-report', loadChildren: () => import('../report/disconnection-report/disconnection-report.module').then(m => m.DisconnectionReportModule) },
  { path: 'spare-number-report', loadChildren: () => import('../report/spare-number-report/spare-number-report.module').then(m => m.SpareNumberReportModule) },
  { path: 'user-role-report', loadChildren: () => import('../report/user-role-report/user-role-report.module').then(m => m.UserRoleReportModule) },
  { path: 'user-report', loadChildren: () => import('../report/user-report/user-report.module').then(m => m.UserReportModule) },
  { path: 'user-mobilenumber-report/:uid', loadChildren: () => import('../report/user-mobile-number-report/user-mobile-number-report.module').then(m => m.UserMobileNumberReportModule) },
  { path: 'refurbished-product', loadChildren: () => import('../report/refurbished-product-Report/refurbished-product.module').then(m => m.RefurbishedProductModule) },
  { path: 'schedule-report', loadChildren: () => import('../schedule-report/schedule-report.module').then(m => m.ScheduleReportModule) },
  { path: 'saved-report', loadChildren: () => import('../schedule-report/saved-report/saved-report.module').then(m => m.SavedReportModule) },
  { path: 'manage-address', loadChildren: () => import('../manage-address/manage-address.module').then(m => m.ManageAddressModule) },
  { path: 'tariff-maintenance', loadChildren: () => import('../tariff-maintenance/tariff-maintenance.module').then(m => m.TariffMaintenanceModule) },
  { path: 'manage-reporting-group/:reportinggroup/:rid', loadChildren: () => import('../manage-reporting-group/manage-reporting-group.module').then(m => m.ManagerReportingGroupModule) },
  { path: 'product-maintenance', loadChildren: () => import('../product-maintenance/product-maintenance.module').then(m => m.ProductMaintenanceModule) },
  { path: 'reporting-group-relations', loadChildren: () => import('../manage-reporting-group/reporting-group-relationship/reporting-group-relationship.module').then(m => m.ReportingGroupRelModule) },
  { path: 'add-refurbished-product', loadChildren: () => import('../refurbished-product/add-refurbished-product.module').then(m => m.AddRefurbishedProductModule) },
  { path: 'my-number', loadChildren: () => import('../report/my-number-report/my-number-report.module').then(m => m.MyNumberReportModule) },
  { path: 'care', loadChildren: () => import('../care/care.module').then(m => m.CareModule) },
  { path: 'add-bulk-asset', loadChildren: () => import('../bulkupload/add-bulk-asset/add-bulk-asset.module').then(m => m.AddBulkAssetModule) },
  { path: 'add-bulk-ctn', loadChildren: () => import('../bulkupload/add-bulk-ctn/add-bulk-ctn.module').then(m => m.AddBulkCtnModule) },
  { path: 'add-bulk-user', loadChildren: () => import('../bulkupload/add-bulk-user/add-bulk-user.module').then(m => m.AddBulkUserModule) },
  { path: 'edit-bulk-ctn', loadChildren: () => import('../bulkupload/edit-bulk-ctn/edit-bulk-ctn.module').then(m => m.EditBulkCTNModule) },

];

